name: TeamBattle
author: Jamy
main: be.jamy.teambattle.TeamBattle
version: 0.1b
softdepend: tagAPI

commands:
   tb:
      description: Main TeamBattle user commands
      usage: /tb <action> [Params]
      permission: TeamBattle.user
      permission-message: You don't have permissions for TeamBattle!